stages:
  - build

full_build:
  stage: build
  only:
    - master
    - develop
  script:
    - apt-get-repository -y ppa:cwchien/gradle
    - apt-get update
    - apt-get install --yes --force-yes gradle
    - gradle setupCIWorkspace
    - gradle build
  artifacts:
    paths:
      - build/libs/
  cache:
    untracked: true
    paths:
      - /