stages:
  - build

full_build:
  stage: build
  only:
    - master
    - develop
  script:
    - apt-get install gradle -y
    - gradle setupDecompWorkspace
    - gradle build
  artifacts:
    paths:
      - build/libs/
  cache:
    untracked: true
    paths:
      - /