#!/usr/bin/env python3
"""
Converts v3's OBJ models (art/obj_models) into models NeoForge's OBJ loader (`neoforge:obj`) can use, and copies their
textures into the block atlas. Run from the repo root after changing the table below, and commit the outputs:

    python3 tools/gen_obj.py

The output OBJs are normalized, so model JSONs and renderers need no scaling or offset:
- Positions are in blocks, with the origin at the lowest corner of the block the model belongs to (for a multiblock,
  its anchor block). v3's models were centred on x/z = 0 (and some on y = 0), and the crystal cluster was drawn at 1/100
  scale; those transforms are applied here.
- Every face has a material from models/block/obj/femtocraft.mtl (the loader draws nothing for faces without one).
  `base` uses the model's `#texture` slot; `color` is v3's colour layer (`#color`, tint index 0, fullbright), added as
  a copy of the base faces pushed out along their normals so the two do not z-fight; `tinted` is `#texture` with tint
  index 0, fullbright.
- `o`/`g` nesting is flattened to top-level groups, named as in v3, for the model JSONs' `visibility` maps.
- UVs keep v3's orientation; model JSONs set `flip_v` (v3's renderer drew `1 - v`).
"""
import os
import shutil

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ART = os.path.join(ROOT, "art", "obj_models")
ASSETS = os.path.join(ROOT, "src", "main", "resources", "assets", "femtocraft")
OBJ_OUT = os.path.join(ASSETS, "models", "block", "obj")
TEX_OUT = os.path.join(ASSETS, "textures", "block", "obj")

# Pushes the colour layer off the base faces, in blocks.
COLOR_OFFSET = 0.004

MTL = """# Generated by tools/gen_obj.py. Materials shared by Femtocraft's OBJ models; textures come from each model JSON.
newmtl base
Ka 0 0 0
Kd 1 1 1
map_Kd #texture

newmtl color
Ka 1 1 1
Kd 1 1 1
neoforge_TintIndex 0
map_Kd #color

newmtl tinted
Ka 1 1 1
Kd 1 1 1
neoforge_TintIndex 0
map_Kd #texture
"""

# out name: (source obj, offset (x, y, z) added after scaling, scale, material per group, groups with a colour layer)
# Material per group: a function from group name to "base" or "tinted".
MODELS = {
    "crystal_mount": ("crystal_mount/crystal_mount.obj", (0.5, 0, 0.5), 1.0, lambda g: "base", set()),
    "wire_thin": ("wire/wire_thin.obj", (0.5, 0.5, 0.5), 1.0, lambda g: "base", "all"),
    "frame": ("frame/frame.obj", (0.5, 0, 0.5), 1.0, lambda g: "base", set()),
    # Anchored at the lowest corner of the 2x3x2 chamber; v3 centred it on the 2x2 footprint.
    "germination_chamber": ("growth_chamber/growth chamber.obj", (1, 0, 1), 1.0, lambda g: "base", {"Base", "Middle", "Top", "Sprinkler1", "Sprinkler2", "Sprinkler3"}),
    "crystal_cluster": ("crystal_cluster/crystals.obj", (0.5, 0, 0.5), 0.01, lambda g: "tinted", set()),
}

# out texture name: source png (relative to art/obj_models)
TEXTURES = {
    "crystal_mount": "crystal_mount/crystal_mount.png",
    "wire_thin": "wire/wire_thin.png",
    "wire_thin_color": "wire/wire_thin_color.png",
    "wire_thin_power": "wire/wire_thin_power.png",
    "wire_thin_power_color": "wire/wire_thin_power_color.png",
    "frame": "frame/frame.png",
    "germination_chamber": "growth_chamber/growth chamber.png",
    "germination_chamber_color": "growth_chamber/growth chamber_color.png",
    "crystal_cluster": "crystal_cluster/crystals texture 64x64.png",
}


def parse(path):
    v, vt, vn, groups = [], [], [], []  # groups: [name, [faces]]; face: [(vi, ti, ni)] 0-based, None if absent
    current = None
    with open(path, encoding="utf-8", errors="replace") as f:
        for raw in f:
            p = raw.split()
            if not p:
                continue
            if p[0] == "v":
                v.append(tuple(float(x) for x in p[1:4]))
            elif p[0] == "vt":
                vt.append(tuple(float(x) for x in p[1:3]))
            elif p[0] == "vn":
                vn.append(tuple(float(x) for x in p[1:4]))
            elif p[0] in ("g", "o"):
                name = " ".join(p[1:]) or "default"
                # Repeated names continue the same group (v3's exporter wrote `o X` then `g X`).
                current = next((g for g in groups if g[0] == name), None)
                if current is None:
                    current = [name, []]
                    groups.append(current)
            elif p[0] == "f":
                if current is None:
                    current = ["default", []]
                    groups.append(current)
                face = []
                for corner in p[1:]:
                    parts = corner.split("/")
                    idx = [int(x) - 1 if x else None for x in parts] + [None] * (3 - len(parts))
                    face.append(tuple(idx[:3]))
                current[1].append(face)
    return v, vt, vn, groups


def normal(face, v, vn):
    if all(c[2] is not None for c in face) and vn:
        n = [sum(vn[c[2]][i] for c in face) for i in range(3)]
    else:
        a, b, c = (v[x[0]] for x in face[:3])
        u = [b[i] - a[i] for i in range(3)]
        w = [c[i] - a[i] for i in range(3)]
        n = [u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2], u[0] * w[1] - u[1] * w[0]]
    length = sum(x * x for x in n) ** 0.5 or 1.0
    return [x / length for x in n]


def fmt(x):
    s = f"{x:.6f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def convert(name, src, offset, scale, material, color_groups):
    v, vt, vn, groups = parse(os.path.join(ART, src))
    v = [tuple(c * scale + offset[i] for i, c in enumerate(p)) for p in v]
    out = [f"# Generated by tools/gen_obj.py from art/obj_models/{src}; blocks, origin at the block's lowest corner.",
           "mtllib femtocraft.mtl"]
    out += [f"v {fmt(x)} {fmt(y)} {fmt(z)}" for x, y, z in v]
    out += [f"vt {fmt(a)} {fmt(b)}" for a, b in vt]
    out += [f"vn {fmt(x)} {fmt(y)} {fmt(z)}" for x, y, z in vn]
    extra = []  # pushed-out vertices for colour layers, appended after v
    body = []

    def corner(c, vi):
        t = "" if c[1] is None else str(c[1] + 1)
        n = "" if c[2] is None else str(c[2] + 1)
        if not t and not n:
            return str(vi + 1)
        return f"{vi + 1}/{t}/{n}" if n else f"{vi + 1}/{t}"

    for gname, faces in groups:
        body.append(f"g {gname.replace(' ', '_')}")
        body.append(f"usemtl {material(gname)}")
        body += ["f " + " ".join(corner(c, c[0]) for c in face) for face in faces]
        if color_groups == "all" or gname in color_groups:
            body.append("usemtl color")
            for face in faces:
                n = normal(face, v, vn)
                corners = []
                for c in face:
                    p = v[c[0]]
                    extra.append(tuple(p[i] + n[i] * COLOR_OFFSET for i in range(3)))
                    corners.append(corner(c, len(v) + len(extra) - 1))
                body.append("f " + " ".join(corners))
    out += [f"v {fmt(x)} {fmt(y)} {fmt(z)}" for x, y, z in extra]
    out += body
    with open(os.path.join(OBJ_OUT, f"{name}.obj"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    xs, ys, zs = zip(*v)
    print(f"{name}: {len(groups)} groups, bounds x[{min(xs):.2f},{max(xs):.2f}] y[{min(ys):.2f},{max(ys):.2f}] z[{min(zs):.2f},{max(zs):.2f}]")


def main():
    os.makedirs(OBJ_OUT, exist_ok=True)
    os.makedirs(TEX_OUT, exist_ok=True)
    with open(os.path.join(OBJ_OUT, "femtocraft.mtl"), "w", encoding="utf-8", newline="\n") as f:
        f.write(MTL)
    for name, spec in MODELS.items():
        convert(name, *spec)
    for name, src in TEXTURES.items():
        shutil.copyfile(os.path.join(ART, src), os.path.join(TEX_OUT, f"{name}.png"))


if __name__ == "__main__":
    main()
